### ISSUE TITLE
Pipeline timeout error

### ISSUE THREAD

**Issue by nicosammito** [code0-tech/pictor#218]
For some weird reason the snapshot pipeline fails after some time with this error:

```
FAIL browser: chromium src/components/d-screen/DScreen.stories.tsx (15.648 s)
    ● Dashboard Screen › DashboardScreenExample › smoke-test
  
      thrown: "Exceeded timeout of 15000 ms for a test.
      Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."
  
        127 |                     <Badge>Home</Badge>
        128 |                     <Text size={"sm"} mx={0.5}>/</Text>
      > 129 |                     <Badge>...</Badge>
            |             ^
        130 |                     <Text size={"sm"} mx={0.5}>/</Text>
        131 |                     <Badge>Sagittarius</Badge>
        132 |                 </DScreen.BarContent>
  
        at src/components/d-screen/DScreen.stories.tsx:129:13
        at src/components/d-screen/DScreen.stories.tsx:128:9
        at Object.<anonymous> (src/components/d-screen/DScreen.stories.tsx:127:5)
  
```

have a look into the Pipeline: https://github.com/code0-tech/pictor/actions/runs/11525827206/job/32088845710

**Comment by Taucher2003** [comment]
I haven't looked at it in detail yet, but it might be caused by https://github.com/tabler/tabler-icons/issues/1233

**Comment by nicosammito** [comment]
> I haven't looked at it in detail yet, but it might be caused by [tabler/tabler-icons#1233](https://github.com/tabler/tabler-icons/issues/1233)

tbh this complete error does not make any sense because it tries to create a snapshot from a screen that is not existing (commented out).

https://github.com/code0-tech/pictor/blob/renovate/tabler-icons-react-3.x/src/components/d-screen/DScreen.stories.tsx

**Comment by nicosammito** [comment]
nvm the error still exists. Probably this is because of tabler icons

**Comment by nicosammito** [comment]
Because we can't rly do something now, we should wait until tabler icons fixes or reverses the changes of dynamic icon imports.

**Comment by nicosammito** [comment]
still an issue
